/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import * as THREE from "three";

export function Intro(props) {
  const { viewport } = useThree();
  const { nodes, materials } = useGLTF("/Greeting_Text.glb");

  return (
    <group
      {...props}
      dispose={null}
      scale={0.74}
      position={[0, viewport.height * 0 + 0.3, -0.4]}
    >
      <mesh
        geometry={nodes.quilkes.geometry}
        material={materials.Material}
        position={[-0.297, 0.337, 0.028]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshBasicMaterial color={"#915eFF"} />
      </mesh>
      <mesh
        geometry={nodes.hidden.geometry}
        material={materials["Material.003"]}
        position={[-0.297, 0.337, 0.028]}
        rotation={[Math.PI / 2, 0, 0]}
      ></mesh>

      <mesh
        geometry={nodes.others.geometry}
        material={materials["Material.002"]}
        position={[-0.297, 0.337, 0.028]}
        rotation={[Math.PI / 2, 0, 0]}
      ></mesh>
    </group>
  );
}

useGLTF.preload("/Greeting_Text.glb");
