/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { RigidBody } from "@react-three/rapier";

export function Bowl(props) {
  const { nodes, materials } = useGLTF("models/bowl.glb");
  const { viewport } = useThree();

  return (
    <RigidBody
      type="fixed"
      friction={20}
      colliders="trimesh"
      position={[-1.3, -viewport.height * 2.2526, 5]}
    >
      <group {...props} dispose={null} scale={0.5}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere.geometry}
          material={materials.Material}
          position={[0, -0.52, 0]}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload("models/bowl.glb");
