/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { RigidBody } from "@react-three/rapier";

export function Tunnel(props) {
  const { nodes, materials } = useGLTF("models/tunnel.glb");
  const { viewport } = useThree();

  return (
    <RigidBody
      type="fixed"
      colliders="trimesh"
      position={[-2.2, -viewport.height * 2.17, 1.6]}
      rotation={[0, -Math.PI * 4.02, 0]}
    >
      <group {...props} dispose={null} scale={0.037} rotation-y={3.16}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials.Material}
          position={[-0.263, 55.7, 0.014]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials.Material}
          position={[-24.747, 69.37, 9.556]}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload("models/tunnel.glb");
