/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useThree } from "@react-three/fiber";
import { RigidBody } from "@react-three/rapier";
import { useControls } from "leva";

export function Wall(props) {
  const { nodes, materials } = useGLTF("models/wall.glb");
  const { viewport } = useThree();

  return (
    <group
      {...props}
      dispose={null}
      rotation-y={-Math.PI / 2}
      position-y={-viewport.height * 1}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[viewport.height * 3, 1, viewport.width]}
      >
        <meshStandardMaterial color={"#37b2c7"} toneMapped={false} />
      </mesh>
    </group>
  );
}

useGLTF.preload("models/wall.glb");
